---
dist: xenial
language: python
python: "3.8"
os: linux
services:
  - docker
install:
  - pip install -r requirements-test.txt
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    if: branch = master
    on_success: change
    on_failure: always
    recipients:
      - desarrollo.benders@idealista.com
