---
- name: Confluence | Setting confluence path in config
  lineinfile:
    path:
      "{{ confluence_home_path }}/{{ confluence_pkg }}/confluence/\
      WEB-INF/classes/confluence-init.properties"
    regexp: 'confluence\.home'
    line: "confluence.home={{ confluence_home_path }}/{{ confluence_pkg }}"
    state: present
  notify: Confluence | Service restart

- name: Confluence | Setting confluence config
  template:
    src: templates/server.xml.j2
    dest: "{{ confluence_home_path }}/{{ confluence_pkg }}/conf/server.xml"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group }}"
    mode: '0644'
  notify: Confluence | Service restart
