---
- name: Confluence | Setting confluence path in config
  lineinfile:
    path:
      "{{ confluence_home_path }}/{{ confluence_pkg }}/confluence/\
      WEB-INF/classes/confluence-init.properties"
    regexp: 'confluence\.home'
    line: "confluence.home={{ confluence_data_path }}"
    state: present
  notify: Confluence | Service restart

- name: Confluence | Setting confluence config
  template:
    src: templates/server.xml.j2
    dest: "{{ confluence_home_path }}/{{ confluence_pkg }}/conf/server.xml"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group }}"
    mode: '0644'
  notify: Confluence | Service restart

- name: Confluence | Setting Catalina config
  template:
    src: templates/setenv.sh.j2
    dest: "{{ confluence_home_path }}/{{ confluence_pkg }}/bin/setenv.sh"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group }}"
    mode: '0644'
  notify: Confluence | Service restart

- name: Confluence | Setting logs location
  template:
    src: templates/logging.properties.j2
    dest:
      "{{ confluence_home_path }}/{{ confluence_pkg }}/conf/logging.properties"
    mode: '0644'
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group }}"
  notify: Confluence | Service restart

- name: Confluence | Copying logrotate config
  template:
    src: "{{ confluence_logrotate_config_file }}"
    dest: /etc/logrotate.d/confluence
    mode: 0644
    owner: root
    group: root
  when: confluence_logrotate_enabled | bool
