---
java_jdk_vendor: adoptopenjdk
java_open_jdk_version_major: 8
java_open_jdk_home_dir: "adoptopenjdk-{{ java_open_jdk_version_major }}-hotspot-amd64"
java_open_jdk_home: "/usr/lib/jvm/{{ java_open_jdk_home_dir }}"
