---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint .
  ansible-lint .

platforms:
  - name: confluence
    image: ${MOLECULE_DISTRO:-debian:buster-slim}
    privileged: true
    published_ports:
      - "80:80"
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    groups:
      - confluence_group
    command: '/lib/systemd/systemd'
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    stop_signal: 'RTMIN+3'

provisioner:
  name: ansible

verifier:
  name: ansible
